parser: "@babel/eslint-parser"
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  requireConfigFile: false
env:
  es2020: true
  node: true
extends:
  - airbnb-base
rules:
  max-len: [2, 180]
  valid-jsdoc: 1
overrides:
    - env:
        mocha: true
        node: true
      plugins:
        - mocha
      files:
        - "tests/*.test.js"
        - "tests/**/*.test.js"
